@host = http://localhost
@port = 5080

@RestaurantsAPI_HostAddress = {{host}}:{{port}}

### Get all restaurants
GET {{RestaurantsAPI_HostAddress}}/api/restaurants
Accept: application/json

### Get restaurant by ID
GET {{RestaurantsAPI_HostAddress}}/api/restaurants/9
Accept: application/json